// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package com.hoolai.ccgames.protocol;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.BaseCommand)
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<BaseCommand> {

    /**
     * <code>required .Common.BaseCommand.CommandType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .Common.BaseCommand.CommandType type = 1;</code>
     */
    com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType getType();

    /**
     * <code>optional int32 msg_id = 2;</code>
     */
    boolean hasMsgId();
    /**
     * <code>optional int32 msg_id = 2;</code>
     */
    int getMsgId();

    /**
     * <code>optional int32 props = 3;</code>
     */
    boolean hasProps();
    /**
     * <code>optional int32 props = 3;</code>
     */
    int getProps();
  }
  /**
   * Protobuf type {@code Common.BaseCommand}
   */
  public static final class BaseCommand extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        BaseCommand> implements
      // @@protoc_insertion_point(message_implements:Common.BaseCommand)
      BaseCommandOrBuilder {
    // Use BaseCommand.newBuilder() to construct.
    private BaseCommand(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.hoolai.ccgames.protocol.Command.BaseCommand, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseCommand defaultInstance;
    public static BaseCommand getDefaultInstance() {
      return defaultInstance;
    }

    public BaseCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType value = com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              msgId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              props_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoolai.ccgames.protocol.Command.internal_static_Common_BaseCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoolai.ccgames.protocol.Command.internal_static_Common_BaseCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoolai.ccgames.protocol.Command.BaseCommand.class, com.hoolai.ccgames.protocol.Command.BaseCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseCommand> PARSER =
        new com.google.protobuf.AbstractParser<BaseCommand>() {
      public BaseCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseCommand> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Common.BaseCommand.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AUTH_LOGIN = 1;</code>
       */
      AUTH_LOGIN(0, 1),
      /**
       * <code>AUTH_LOGOUT = 2;</code>
       */
      AUTH_LOGOUT(1, 2),
      /**
       * <code>GET_UUID_RANGE = 7;</code>
       */
      GET_UUID_RANGE(2, 7),
      /**
       * <code>GET_USER_ID = 8;</code>
       */
      GET_USER_ID(3, 8),
      /**
       * <code>NEW_USER = 9;</code>
       */
      NEW_USER(4, 9),
      /**
       * <code>QUERY_USER_GOLD = 10;</code>
       */
      QUERY_USER_GOLD(5, 10),
      /**
       * <code>CHANGE_USER_GOLD = 11;</code>
       */
      CHANGE_USER_GOLD(6, 11),
      /**
       * <code>SET_USER_GOLD = 12;</code>
       */
      SET_USER_GOLD(7, 12),
      /**
       * <code>QUERY_USER_HOOLAI_GOLD = 15;</code>
       */
      QUERY_USER_HOOLAI_GOLD(8, 15),
      /**
       * <code>CHANGE_USER_HOOLAI_GOLD = 16;</code>
       */
      CHANGE_USER_HOOLAI_GOLD(9, 16),
      /**
       * <code>SET_USER_HOOLAI_GOLD = 17;</code>
       */
      SET_USER_HOOLAI_GOLD(10, 17),
      /**
       * <code>QUERY_USER_MASTER_POINT = 20;</code>
       */
      QUERY_USER_MASTER_POINT(11, 20),
      /**
       * <code>CHANGE_USER_MASTER_POINT = 21;</code>
       */
      CHANGE_USER_MASTER_POINT(12, 21),
      /**
       * <code>SET_USER_MASTER_POINT = 22;</code>
       */
      SET_USER_MASTER_POINT(13, 22),
      /**
       * <code>QUERY_USER_HELP_USED = 25;</code>
       */
      QUERY_USER_HELP_USED(14, 25),
      /**
       * <code>INCR_USER_HELP_USED = 26;</code>
       */
      INCR_USER_HELP_USED(15, 26),
      /**
       * <code>QUERY_USER_ITEM = 50;</code>
       */
      QUERY_USER_ITEM(16, 50),
      /**
       * <code>CHANGE_USER_ITEM = 51;</code>
       */
      CHANGE_USER_ITEM(17, 51),
      /**
       * <code>SET_USER_ITEM = 52;</code>
       */
      SET_USER_ITEM(18, 52),
      /**
       * <code>QUERY_USER_ITEM_USED = 55;</code>
       */
      QUERY_USER_ITEM_USED(19, 55),
      /**
       * <code>ADD_USER_ITEM_USED = 56;</code>
       */
      ADD_USER_ITEM_USED(20, 56),
      /**
       * <code>SET_USER_ITEM_USED = 57;</code>
       */
      SET_USER_ITEM_USED(21, 57),
      /**
       * <code>QUERY_USER_ITEM_GIVE = 60;</code>
       */
      QUERY_USER_ITEM_GIVE(22, 60),
      /**
       * <code>ADD_USER_ITEM_GIVE = 61;</code>
       */
      ADD_USER_ITEM_GIVE(23, 61),
      /**
       * <code>SET_USER_ITEM_GIVE = 62;</code>
       */
      SET_USER_ITEM_GIVE(24, 62),
      /**
       * <code>QUERY_USER_SAFEBOX = 65;</code>
       */
      QUERY_USER_SAFEBOX(25, 65),
      /**
       * <code>CHANGE_USER_SAFEBOX = 66;</code>
       */
      CHANGE_USER_SAFEBOX(26, 66),
      /**
       * <code>SET_USER_SAFEBOX = 67;</code>
       */
      SET_USER_SAFEBOX(27, 67),
      /**
       * <code>HEART_BEAT = 88;</code>
       */
      HEART_BEAT(28, 88),
      /**
       * <code>ERR_CMD = 100;</code>
       */
      ERR_CMD(29, 100),
      ;

      /**
       * <code>AUTH_LOGIN = 1;</code>
       */
      public static final int AUTH_LOGIN_VALUE = 1;
      /**
       * <code>AUTH_LOGOUT = 2;</code>
       */
      public static final int AUTH_LOGOUT_VALUE = 2;
      /**
       * <code>GET_UUID_RANGE = 7;</code>
       */
      public static final int GET_UUID_RANGE_VALUE = 7;
      /**
       * <code>GET_USER_ID = 8;</code>
       */
      public static final int GET_USER_ID_VALUE = 8;
      /**
       * <code>NEW_USER = 9;</code>
       */
      public static final int NEW_USER_VALUE = 9;
      /**
       * <code>QUERY_USER_GOLD = 10;</code>
       */
      public static final int QUERY_USER_GOLD_VALUE = 10;
      /**
       * <code>CHANGE_USER_GOLD = 11;</code>
       */
      public static final int CHANGE_USER_GOLD_VALUE = 11;
      /**
       * <code>SET_USER_GOLD = 12;</code>
       */
      public static final int SET_USER_GOLD_VALUE = 12;
      /**
       * <code>QUERY_USER_HOOLAI_GOLD = 15;</code>
       */
      public static final int QUERY_USER_HOOLAI_GOLD_VALUE = 15;
      /**
       * <code>CHANGE_USER_HOOLAI_GOLD = 16;</code>
       */
      public static final int CHANGE_USER_HOOLAI_GOLD_VALUE = 16;
      /**
       * <code>SET_USER_HOOLAI_GOLD = 17;</code>
       */
      public static final int SET_USER_HOOLAI_GOLD_VALUE = 17;
      /**
       * <code>QUERY_USER_MASTER_POINT = 20;</code>
       */
      public static final int QUERY_USER_MASTER_POINT_VALUE = 20;
      /**
       * <code>CHANGE_USER_MASTER_POINT = 21;</code>
       */
      public static final int CHANGE_USER_MASTER_POINT_VALUE = 21;
      /**
       * <code>SET_USER_MASTER_POINT = 22;</code>
       */
      public static final int SET_USER_MASTER_POINT_VALUE = 22;
      /**
       * <code>QUERY_USER_HELP_USED = 25;</code>
       */
      public static final int QUERY_USER_HELP_USED_VALUE = 25;
      /**
       * <code>INCR_USER_HELP_USED = 26;</code>
       */
      public static final int INCR_USER_HELP_USED_VALUE = 26;
      /**
       * <code>QUERY_USER_ITEM = 50;</code>
       */
      public static final int QUERY_USER_ITEM_VALUE = 50;
      /**
       * <code>CHANGE_USER_ITEM = 51;</code>
       */
      public static final int CHANGE_USER_ITEM_VALUE = 51;
      /**
       * <code>SET_USER_ITEM = 52;</code>
       */
      public static final int SET_USER_ITEM_VALUE = 52;
      /**
       * <code>QUERY_USER_ITEM_USED = 55;</code>
       */
      public static final int QUERY_USER_ITEM_USED_VALUE = 55;
      /**
       * <code>ADD_USER_ITEM_USED = 56;</code>
       */
      public static final int ADD_USER_ITEM_USED_VALUE = 56;
      /**
       * <code>SET_USER_ITEM_USED = 57;</code>
       */
      public static final int SET_USER_ITEM_USED_VALUE = 57;
      /**
       * <code>QUERY_USER_ITEM_GIVE = 60;</code>
       */
      public static final int QUERY_USER_ITEM_GIVE_VALUE = 60;
      /**
       * <code>ADD_USER_ITEM_GIVE = 61;</code>
       */
      public static final int ADD_USER_ITEM_GIVE_VALUE = 61;
      /**
       * <code>SET_USER_ITEM_GIVE = 62;</code>
       */
      public static final int SET_USER_ITEM_GIVE_VALUE = 62;
      /**
       * <code>QUERY_USER_SAFEBOX = 65;</code>
       */
      public static final int QUERY_USER_SAFEBOX_VALUE = 65;
      /**
       * <code>CHANGE_USER_SAFEBOX = 66;</code>
       */
      public static final int CHANGE_USER_SAFEBOX_VALUE = 66;
      /**
       * <code>SET_USER_SAFEBOX = 67;</code>
       */
      public static final int SET_USER_SAFEBOX_VALUE = 67;
      /**
       * <code>HEART_BEAT = 88;</code>
       */
      public static final int HEART_BEAT_VALUE = 88;
      /**
       * <code>ERR_CMD = 100;</code>
       */
      public static final int ERR_CMD_VALUE = 100;


      public final int getNumber() { return value; }

      public static CommandType valueOf(int value) {
        switch (value) {
          case 1: return AUTH_LOGIN;
          case 2: return AUTH_LOGOUT;
          case 7: return GET_UUID_RANGE;
          case 8: return GET_USER_ID;
          case 9: return NEW_USER;
          case 10: return QUERY_USER_GOLD;
          case 11: return CHANGE_USER_GOLD;
          case 12: return SET_USER_GOLD;
          case 15: return QUERY_USER_HOOLAI_GOLD;
          case 16: return CHANGE_USER_HOOLAI_GOLD;
          case 17: return SET_USER_HOOLAI_GOLD;
          case 20: return QUERY_USER_MASTER_POINT;
          case 21: return CHANGE_USER_MASTER_POINT;
          case 22: return SET_USER_MASTER_POINT;
          case 25: return QUERY_USER_HELP_USED;
          case 26: return INCR_USER_HELP_USED;
          case 50: return QUERY_USER_ITEM;
          case 51: return CHANGE_USER_ITEM;
          case 52: return SET_USER_ITEM;
          case 55: return QUERY_USER_ITEM_USED;
          case 56: return ADD_USER_ITEM_USED;
          case 57: return SET_USER_ITEM_USED;
          case 60: return QUERY_USER_ITEM_GIVE;
          case 61: return ADD_USER_ITEM_GIVE;
          case 62: return SET_USER_ITEM_GIVE;
          case 65: return QUERY_USER_SAFEBOX;
          case 66: return CHANGE_USER_SAFEBOX;
          case 67: return SET_USER_SAFEBOX;
          case 88: return HEART_BEAT;
          case 100: return ERR_CMD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.hoolai.ccgames.protocol.Command.BaseCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CommandType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Common.BaseCommand.CommandType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType type_;
    /**
     * <code>required .Common.BaseCommand.CommandType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Common.BaseCommand.CommandType type = 1;</code>
     */
    public com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType getType() {
      return type_;
    }

    public static final int MSG_ID_FIELD_NUMBER = 2;
    private int msgId_;
    /**
     * <code>optional int32 msg_id = 2;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 msg_id = 2;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int PROPS_FIELD_NUMBER = 3;
    private int props_;
    /**
     * <code>optional int32 props = 3;</code>
     */
    public boolean hasProps() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 props = 3;</code>
     */
    public int getProps() {
      return props_;
    }

    private void initFields() {
      type_ = com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType.AUTH_LOGIN;
      msgId_ = 0;
      props_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.hoolai.ccgames.protocol.Command.BaseCommand>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, msgId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, props_);
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, props_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hoolai.ccgames.protocol.Command.BaseCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.protocol.Command.BaseCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Command.BaseCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.protocol.Command.BaseCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Command.BaseCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.protocol.Command.BaseCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Command.BaseCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hoolai.ccgames.protocol.Command.BaseCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Command.BaseCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.protocol.Command.BaseCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hoolai.ccgames.protocol.Command.BaseCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Common.BaseCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.hoolai.ccgames.protocol.Command.BaseCommand, Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.BaseCommand)
        com.hoolai.ccgames.protocol.Command.BaseCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoolai.ccgames.protocol.Command.internal_static_Common_BaseCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoolai.ccgames.protocol.Command.internal_static_Common_BaseCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoolai.ccgames.protocol.Command.BaseCommand.class, com.hoolai.ccgames.protocol.Command.BaseCommand.Builder.class);
      }

      // Construct using com.hoolai.ccgames.protocol.Command.BaseCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType.AUTH_LOGIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        props_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoolai.ccgames.protocol.Command.internal_static_Common_BaseCommand_descriptor;
      }

      public com.hoolai.ccgames.protocol.Command.BaseCommand getDefaultInstanceForType() {
        return com.hoolai.ccgames.protocol.Command.BaseCommand.getDefaultInstance();
      }

      public com.hoolai.ccgames.protocol.Command.BaseCommand build() {
        com.hoolai.ccgames.protocol.Command.BaseCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hoolai.ccgames.protocol.Command.BaseCommand buildPartial() {
        com.hoolai.ccgames.protocol.Command.BaseCommand result = new com.hoolai.ccgames.protocol.Command.BaseCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.props_ = props_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoolai.ccgames.protocol.Command.BaseCommand) {
          return mergeFrom((com.hoolai.ccgames.protocol.Command.BaseCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoolai.ccgames.protocol.Command.BaseCommand other) {
        if (other == com.hoolai.ccgames.protocol.Command.BaseCommand.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasProps()) {
          setProps(other.getProps());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoolai.ccgames.protocol.Command.BaseCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoolai.ccgames.protocol.Command.BaseCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType type_ = com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType.AUTH_LOGIN;
      /**
       * <code>required .Common.BaseCommand.CommandType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Common.BaseCommand.CommandType type = 1;</code>
       */
      public com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType getType() {
        return type_;
      }
      /**
       * <code>required .Common.BaseCommand.CommandType type = 1;</code>
       */
      public Builder setType(com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Common.BaseCommand.CommandType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.hoolai.ccgames.protocol.Command.BaseCommand.CommandType.AUTH_LOGIN;
        onChanged();
        return this;
      }

      private int msgId_ ;
      /**
       * <code>optional int32 msg_id = 2;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 msg_id = 2;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>optional int32 msg_id = 2;</code>
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000002;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msg_id = 2;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = 0;
        onChanged();
        return this;
      }

      private int props_ ;
      /**
       * <code>optional int32 props = 3;</code>
       */
      public boolean hasProps() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 props = 3;</code>
       */
      public int getProps() {
        return props_;
      }
      /**
       * <code>optional int32 props = 3;</code>
       */
      public Builder setProps(int value) {
        bitField0_ |= 0x00000004;
        props_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 props = 3;</code>
       */
      public Builder clearProps() {
        bitField0_ = (bitField0_ & ~0x00000004);
        props_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.BaseCommand)
    }

    static {
      defaultInstance = new BaseCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Common.BaseCommand)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Common_BaseCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Common_BaseCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Common.proto\022\006Common\"\231\006\n\013BaseCommand\022-" +
      "\n\004type\030\001 \002(\0162\037.Common.BaseCommand.Comman" +
      "dType\022\016\n\006msg_id\030\002 \001(\005\022\r\n\005props\030\003 \001(\005\"\261\005\n" +
      "\013CommandType\022\016\n\nAUTH_LOGIN\020\001\022\017\n\013AUTH_LOG" +
      "OUT\020\002\022\022\n\016GET_UUID_RANGE\020\007\022\017\n\013GET_USER_ID" +
      "\020\010\022\014\n\010NEW_USER\020\t\022\023\n\017QUERY_USER_GOLD\020\n\022\024\n" +
      "\020CHANGE_USER_GOLD\020\013\022\021\n\rSET_USER_GOLD\020\014\022\032" +
      "\n\026QUERY_USER_HOOLAI_GOLD\020\017\022\033\n\027CHANGE_USE" +
      "R_HOOLAI_GOLD\020\020\022\030\n\024SET_USER_HOOLAI_GOLD\020" +
      "\021\022\033\n\027QUERY_USER_MASTER_POINT\020\024\022\034\n\030CHANGE",
      "_USER_MASTER_POINT\020\025\022\031\n\025SET_USER_MASTER_" +
      "POINT\020\026\022\030\n\024QUERY_USER_HELP_USED\020\031\022\027\n\023INC" +
      "R_USER_HELP_USED\020\032\022\023\n\017QUERY_USER_ITEM\0202\022" +
      "\024\n\020CHANGE_USER_ITEM\0203\022\021\n\rSET_USER_ITEM\0204" +
      "\022\030\n\024QUERY_USER_ITEM_USED\0207\022\026\n\022ADD_USER_I" +
      "TEM_USED\0208\022\026\n\022SET_USER_ITEM_USED\0209\022\030\n\024QU" +
      "ERY_USER_ITEM_GIVE\020<\022\026\n\022ADD_USER_ITEM_GI" +
      "VE\020=\022\026\n\022SET_USER_ITEM_GIVE\020>\022\026\n\022QUERY_US" +
      "ER_SAFEBOX\020A\022\027\n\023CHANGE_USER_SAFEBOX\020B\022\024\n" +
      "\020SET_USER_SAFEBOX\020C\022\016\n\nHEART_BEAT\020X\022\013\n\007E",
      "RR_CMD\020d*\010\010d\020\200\200\200\200\002B&\n\033com.hoolai.ccgames" +
      ".protocolB\007Command"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Common_BaseCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Common_BaseCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Common_BaseCommand_descriptor,
        new java.lang.String[] { "Type", "MsgId", "Props", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
