// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HB.proto

package com.hoolai.ccgames.protocol;

public final class HB {
  private HB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.hoolai.ccgames.protocol.HB.HeartBeat.cmd);
  }
  public interface HeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HB.HeartBeat)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code HB.HeartBeat}
   */
  public static final class HeartBeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HB.HeartBeat)
      HeartBeatOrBuilder {
    // Use HeartBeat.newBuilder() to construct.
    private HeartBeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeat defaultInstance;
    public static HeartBeat getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoolai.ccgames.protocol.HB.internal_static_HB_HeartBeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoolai.ccgames.protocol.HB.internal_static_HB_HeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoolai.ccgames.protocol.HB.HeartBeat.class, com.hoolai.ccgames.protocol.HB.HeartBeat.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeat> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeat>() {
      public HeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeat> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hoolai.ccgames.protocol.HB.HeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.protocol.HB.HeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.HB.HeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.protocol.HB.HeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.HB.HeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.protocol.HB.HeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.HB.HeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hoolai.ccgames.protocol.HB.HeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.HB.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.protocol.HB.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hoolai.ccgames.protocol.HB.HeartBeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HB.HeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HB.HeartBeat)
        com.hoolai.ccgames.protocol.HB.HeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoolai.ccgames.protocol.HB.internal_static_HB_HeartBeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoolai.ccgames.protocol.HB.internal_static_HB_HeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoolai.ccgames.protocol.HB.HeartBeat.class, com.hoolai.ccgames.protocol.HB.HeartBeat.Builder.class);
      }

      // Construct using com.hoolai.ccgames.protocol.HB.HeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoolai.ccgames.protocol.HB.internal_static_HB_HeartBeat_descriptor;
      }

      public com.hoolai.ccgames.protocol.HB.HeartBeat getDefaultInstanceForType() {
        return com.hoolai.ccgames.protocol.HB.HeartBeat.getDefaultInstance();
      }

      public com.hoolai.ccgames.protocol.HB.HeartBeat build() {
        com.hoolai.ccgames.protocol.HB.HeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hoolai.ccgames.protocol.HB.HeartBeat buildPartial() {
        com.hoolai.ccgames.protocol.HB.HeartBeat result = new com.hoolai.ccgames.protocol.HB.HeartBeat(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoolai.ccgames.protocol.HB.HeartBeat) {
          return mergeFrom((com.hoolai.ccgames.protocol.HB.HeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoolai.ccgames.protocol.HB.HeartBeat other) {
        if (other == com.hoolai.ccgames.protocol.HB.HeartBeat.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoolai.ccgames.protocol.HB.HeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoolai.ccgames.protocol.HB.HeartBeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HB.HeartBeat)
    }

    static {
      defaultInstance = new HeartBeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HB.HeartBeat)
    public static final int CMD_FIELD_NUMBER = 260;
    /**
     * <code>extend .Common.BaseCommand { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.hoolai.ccgames.protocol.Command.BaseCommand,
        com.hoolai.ccgames.protocol.HB.HeartBeat> cmd = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.hoolai.ccgames.protocol.HB.HeartBeat.getDefaultInstance(),
          0,
          com.hoolai.ccgames.protocol.HB.HeartBeat.class,
          com.hoolai.ccgames.protocol.HB.HeartBeat.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HB_HeartBeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HB_HeartBeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010HB.proto\022\002HB\032\014Common.proto\"=\n\tHeartBea" +
      "t20\n\003cmd\022\023.Common.BaseCommand\030\204\002 \001(\0132\r.H" +
      "B.HeartBeatB!\n\033com.hoolai.ccgames.protoc" +
      "olB\002HB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hoolai.ccgames.protocol.Command.getDescriptor(),
        }, assigner);
    internal_static_HB_HeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HB_HeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HB_HeartBeat_descriptor,
        new java.lang.String[] { });
    com.hoolai.ccgames.protocol.Command.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
