// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Info.proto

package com.hoolai.ccgames.protocol;

public final class Info {
  private Info() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.hoolai.ccgames.protocol.Info.RangeUUIDReq.cmd);
    registry.add(com.hoolai.ccgames.protocol.Info.RangeUUIDResp.cmd);
  }
  public interface RangeUUIDReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Info.RangeUUIDReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string platform = 1;</code>
     */
    boolean hasPlatform();
    /**
     * <code>optional string platform = 1;</code>
     */
    java.lang.String getPlatform();
    /**
     * <code>optional string platform = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();

    /**
     * <code>optional string appID = 2;</code>
     */
    boolean hasAppID();
    /**
     * <code>optional string appID = 2;</code>
     */
    java.lang.String getAppID();
    /**
     * <code>optional string appID = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppIDBytes();
  }
  /**
   * Protobuf type {@code Info.RangeUUIDReq}
   */
  public static final class RangeUUIDReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Info.RangeUUIDReq)
      RangeUUIDReqOrBuilder {
    // Use RangeUUIDReq.newBuilder() to construct.
    private RangeUUIDReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RangeUUIDReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RangeUUIDReq defaultInstance;
    public static RangeUUIDReq getDefaultInstance() {
      return defaultInstance;
    }

    public RangeUUIDReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RangeUUIDReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              platform_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              appID_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoolai.ccgames.protocol.Info.internal_static_Info_RangeUUIDReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoolai.ccgames.protocol.Info.internal_static_Info_RangeUUIDReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoolai.ccgames.protocol.Info.RangeUUIDReq.class, com.hoolai.ccgames.protocol.Info.RangeUUIDReq.Builder.class);
    }

    public static com.google.protobuf.Parser<RangeUUIDReq> PARSER =
        new com.google.protobuf.AbstractParser<RangeUUIDReq>() {
      public RangeUUIDReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RangeUUIDReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RangeUUIDReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLATFORM_FIELD_NUMBER = 1;
    private java.lang.Object platform_;
    /**
     * <code>optional string platform = 1;</code>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string platform = 1;</code>
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          platform_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string platform = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPID_FIELD_NUMBER = 2;
    private java.lang.Object appID_;
    /**
     * <code>optional string appID = 2;</code>
     */
    public boolean hasAppID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string appID = 2;</code>
     */
    public java.lang.String getAppID() {
      java.lang.Object ref = appID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string appID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppIDBytes() {
      java.lang.Object ref = appID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      platform_ = "";
      appID_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPlatformBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAppIDBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPlatformBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAppIDBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hoolai.ccgames.protocol.Info.RangeUUIDReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hoolai.ccgames.protocol.Info.RangeUUIDReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Info.RangeUUIDReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Info.RangeUUIDReq)
        com.hoolai.ccgames.protocol.Info.RangeUUIDReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoolai.ccgames.protocol.Info.internal_static_Info_RangeUUIDReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoolai.ccgames.protocol.Info.internal_static_Info_RangeUUIDReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoolai.ccgames.protocol.Info.RangeUUIDReq.class, com.hoolai.ccgames.protocol.Info.RangeUUIDReq.Builder.class);
      }

      // Construct using com.hoolai.ccgames.protocol.Info.RangeUUIDReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        platform_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        appID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoolai.ccgames.protocol.Info.internal_static_Info_RangeUUIDReq_descriptor;
      }

      public com.hoolai.ccgames.protocol.Info.RangeUUIDReq getDefaultInstanceForType() {
        return com.hoolai.ccgames.protocol.Info.RangeUUIDReq.getDefaultInstance();
      }

      public com.hoolai.ccgames.protocol.Info.RangeUUIDReq build() {
        com.hoolai.ccgames.protocol.Info.RangeUUIDReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hoolai.ccgames.protocol.Info.RangeUUIDReq buildPartial() {
        com.hoolai.ccgames.protocol.Info.RangeUUIDReq result = new com.hoolai.ccgames.protocol.Info.RangeUUIDReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.platform_ = platform_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appID_ = appID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoolai.ccgames.protocol.Info.RangeUUIDReq) {
          return mergeFrom((com.hoolai.ccgames.protocol.Info.RangeUUIDReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoolai.ccgames.protocol.Info.RangeUUIDReq other) {
        if (other == com.hoolai.ccgames.protocol.Info.RangeUUIDReq.getDefaultInstance()) return this;
        if (other.hasPlatform()) {
          bitField0_ |= 0x00000001;
          platform_ = other.platform_;
          onChanged();
        }
        if (other.hasAppID()) {
          bitField0_ |= 0x00000002;
          appID_ = other.appID_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoolai.ccgames.protocol.Info.RangeUUIDReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoolai.ccgames.protocol.Info.RangeUUIDReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object platform_ = "";
      /**
       * <code>optional string platform = 1;</code>
       */
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string platform = 1;</code>
       */
      public java.lang.String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            platform_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string platform = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        java.lang.Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string platform = 1;</code>
       */
      public Builder setPlatform(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string platform = 1;</code>
       */
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000001);
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      /**
       * <code>optional string platform = 1;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        platform_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appID_ = "";
      /**
       * <code>optional string appID = 2;</code>
       */
      public boolean hasAppID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string appID = 2;</code>
       */
      public java.lang.String getAppID() {
        java.lang.Object ref = appID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string appID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppIDBytes() {
        java.lang.Object ref = appID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string appID = 2;</code>
       */
      public Builder setAppID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string appID = 2;</code>
       */
      public Builder clearAppID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appID_ = getDefaultInstance().getAppID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string appID = 2;</code>
       */
      public Builder setAppIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appID_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Info.RangeUUIDReq)
    }

    static {
      defaultInstance = new RangeUUIDReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Info.RangeUUIDReq)
    public static final int CMD_FIELD_NUMBER = 270;
    /**
     * <code>extend .Common.BaseCommand { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.hoolai.ccgames.protocol.Command.BaseCommand,
        com.hoolai.ccgames.protocol.Info.RangeUUIDReq> cmd = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.hoolai.ccgames.protocol.Info.RangeUUIDReq.getDefaultInstance(),
          0,
          com.hoolai.ccgames.protocol.Info.RangeUUIDReq.class,
          com.hoolai.ccgames.protocol.Info.RangeUUIDReq.getDefaultInstance());
  }

  public interface RangeUUIDRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Info.RangeUUIDResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 begin = 1;</code>
     */
    boolean hasBegin();
    /**
     * <code>optional int64 begin = 1;</code>
     */
    long getBegin();

    /**
     * <code>optional int64 end = 2;</code>
     */
    boolean hasEnd();
    /**
     * <code>optional int64 end = 2;</code>
     */
    long getEnd();
  }
  /**
   * Protobuf type {@code Info.RangeUUIDResp}
   */
  public static final class RangeUUIDResp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Info.RangeUUIDResp)
      RangeUUIDRespOrBuilder {
    // Use RangeUUIDResp.newBuilder() to construct.
    private RangeUUIDResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RangeUUIDResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RangeUUIDResp defaultInstance;
    public static RangeUUIDResp getDefaultInstance() {
      return defaultInstance;
    }

    public RangeUUIDResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RangeUUIDResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              begin_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              end_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoolai.ccgames.protocol.Info.internal_static_Info_RangeUUIDResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoolai.ccgames.protocol.Info.internal_static_Info_RangeUUIDResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoolai.ccgames.protocol.Info.RangeUUIDResp.class, com.hoolai.ccgames.protocol.Info.RangeUUIDResp.Builder.class);
    }

    public static com.google.protobuf.Parser<RangeUUIDResp> PARSER =
        new com.google.protobuf.AbstractParser<RangeUUIDResp>() {
      public RangeUUIDResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RangeUUIDResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RangeUUIDResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BEGIN_FIELD_NUMBER = 1;
    private long begin_;
    /**
     * <code>optional int64 begin = 1;</code>
     */
    public boolean hasBegin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 begin = 1;</code>
     */
    public long getBegin() {
      return begin_;
    }

    public static final int END_FIELD_NUMBER = 2;
    private long end_;
    /**
     * <code>optional int64 end = 2;</code>
     */
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 end = 2;</code>
     */
    public long getEnd() {
      return end_;
    }

    private void initFields() {
      begin_ = 0L;
      end_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, begin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, end_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, begin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, end_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hoolai.ccgames.protocol.Info.RangeUUIDResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.protocol.Info.RangeUUIDResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hoolai.ccgames.protocol.Info.RangeUUIDResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Info.RangeUUIDResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Info.RangeUUIDResp)
        com.hoolai.ccgames.protocol.Info.RangeUUIDRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoolai.ccgames.protocol.Info.internal_static_Info_RangeUUIDResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoolai.ccgames.protocol.Info.internal_static_Info_RangeUUIDResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoolai.ccgames.protocol.Info.RangeUUIDResp.class, com.hoolai.ccgames.protocol.Info.RangeUUIDResp.Builder.class);
      }

      // Construct using com.hoolai.ccgames.protocol.Info.RangeUUIDResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        begin_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        end_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoolai.ccgames.protocol.Info.internal_static_Info_RangeUUIDResp_descriptor;
      }

      public com.hoolai.ccgames.protocol.Info.RangeUUIDResp getDefaultInstanceForType() {
        return com.hoolai.ccgames.protocol.Info.RangeUUIDResp.getDefaultInstance();
      }

      public com.hoolai.ccgames.protocol.Info.RangeUUIDResp build() {
        com.hoolai.ccgames.protocol.Info.RangeUUIDResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hoolai.ccgames.protocol.Info.RangeUUIDResp buildPartial() {
        com.hoolai.ccgames.protocol.Info.RangeUUIDResp result = new com.hoolai.ccgames.protocol.Info.RangeUUIDResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.begin_ = begin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.end_ = end_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoolai.ccgames.protocol.Info.RangeUUIDResp) {
          return mergeFrom((com.hoolai.ccgames.protocol.Info.RangeUUIDResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoolai.ccgames.protocol.Info.RangeUUIDResp other) {
        if (other == com.hoolai.ccgames.protocol.Info.RangeUUIDResp.getDefaultInstance()) return this;
        if (other.hasBegin()) {
          setBegin(other.getBegin());
        }
        if (other.hasEnd()) {
          setEnd(other.getEnd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoolai.ccgames.protocol.Info.RangeUUIDResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoolai.ccgames.protocol.Info.RangeUUIDResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long begin_ ;
      /**
       * <code>optional int64 begin = 1;</code>
       */
      public boolean hasBegin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 begin = 1;</code>
       */
      public long getBegin() {
        return begin_;
      }
      /**
       * <code>optional int64 begin = 1;</code>
       */
      public Builder setBegin(long value) {
        bitField0_ |= 0x00000001;
        begin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 begin = 1;</code>
       */
      public Builder clearBegin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        begin_ = 0L;
        onChanged();
        return this;
      }

      private long end_ ;
      /**
       * <code>optional int64 end = 2;</code>
       */
      public boolean hasEnd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 end = 2;</code>
       */
      public long getEnd() {
        return end_;
      }
      /**
       * <code>optional int64 end = 2;</code>
       */
      public Builder setEnd(long value) {
        bitField0_ |= 0x00000002;
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 end = 2;</code>
       */
      public Builder clearEnd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        end_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Info.RangeUUIDResp)
    }

    static {
      defaultInstance = new RangeUUIDResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Info.RangeUUIDResp)
    public static final int CMD_FIELD_NUMBER = 271;
    /**
     * <code>extend .Common.BaseCommand { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.hoolai.ccgames.protocol.Command.BaseCommand,
        com.hoolai.ccgames.protocol.Info.RangeUUIDResp> cmd = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.hoolai.ccgames.protocol.Info.RangeUUIDResp.getDefaultInstance(),
          0,
          com.hoolai.ccgames.protocol.Info.RangeUUIDResp.class,
          com.hoolai.ccgames.protocol.Info.RangeUUIDResp.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Info_RangeUUIDReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Info_RangeUUIDReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Info_RangeUUIDResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Info_RangeUUIDResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nInfo.proto\022\004Info\032\014Common.proto\"f\n\014Rang" +
      "eUUIDReq\022\020\n\010platform\030\001 \001(\t\022\r\n\005appID\030\002 \001(" +
      "\t25\n\003cmd\022\023.Common.BaseCommand\030\216\002 \001(\0132\022.I" +
      "nfo.RangeUUIDReq\"c\n\rRangeUUIDResp\022\r\n\005beg" +
      "in\030\001 \001(\003\022\013\n\003end\030\002 \001(\00326\n\003cmd\022\023.Common.Ba" +
      "seCommand\030\217\002 \001(\0132\023.Info.RangeUUIDRespB#\n" +
      "\033com.hoolai.ccgames.protocolB\004Info"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hoolai.ccgames.protocol.Command.getDescriptor(),
        }, assigner);
    internal_static_Info_RangeUUIDReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Info_RangeUUIDReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Info_RangeUUIDReq_descriptor,
        new java.lang.String[] { "Platform", "AppID", });
    internal_static_Info_RangeUUIDResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Info_RangeUUIDResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Info_RangeUUIDResp_descriptor,
        new java.lang.String[] { "Begin", "End", });
    com.hoolai.ccgames.protocol.Command.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
